---
title: "Alperen Köksal - IE360 - Fall 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(data.table)
library(dplyr)
library(zoo)
library(ggplot2)

deprem <- read.csv("C:/Users/a_kok/Desktop/Dersler/IE 360/Kodlar/earthquake.csv")
depremsv <- read.csv("C:/Users/a_kok/Desktop/Dersler/IE 360/Kodlar/depremsv.csv")

deprem <- subset(deprem,deprem["richter"]>5.0)

i = 1
while(i<=length(deprem[["date"]])){
  deprem[i,"date"] <- substr(deprem[i,"date"],1,4)
  i = i+1
}

i = 1
while(i<=length(depremsv[["Ay"]])){
  depremsv[i,"Ay"] <- substr(depremsv[i,"Ay"],1,4)
  i = i+1
}

deprem <- subset(deprem,deprem["date"]<= '2017')
deprem <- subset(deprem,deprem["date"]>= '2009')

# when we plot the histogram we see that in 2011 and 2017 there were big earthquakes which have richter >= 6.5 and in 2012 2013 2014 there were moderately big earthquakes which have richter >= 6.0

ggplot(deprem, aes(richter,)) + geom_histogram(binwidth = 0.05) + facet_grid(date~.)

# when we compare the search volume "deprem" with the real data of earthquakes we see that when the trend is before the most things searching and verifying the occurrence of the big earthquakes that have higher richter values and have bigger impacts.

ggplot(depremsv, aes(deprem,)) + geom_boxplot() + facet_grid(Ay~.)
ggplot(deprem, aes(richter,)) + geom_boxplot() + facet_grid(date~.)




#2

dolar <- read.csv("C:/Users/a_kok/Desktop/Dersler/IE 360/Kodlar/dolarkuru.csv")
dolarsv <- read.csv("C:/Users/a_kok/Desktop/Dersler/IE 360/Kodlar/dolarsv.csv")


dolar <- na.omit(dolar)

i = 1
while(i<=length(dolar[["Tarih"]])){
  dolar[i,"Tarih"] <- substr(dolar[i,"Tarih"],4,10)
  i = i+1
}
i = 1
while(i<=length(dolarsv[["Hafta"]])){
  dolarsv[i,"Hafta"] <- substr(dolarsv[i,"Hafta"],1,7)
  i = i+1
}

# as we see from histogram dollar Turkish Lira rate is increasing almost constantly from first month of 2020 to now and nowadays the rate has some fluctuations and decrease in value ( maybe the decrease cannot be observed very clearly because of the missing data).

ggplot(dolar, aes(kur,)) + geom_histogram(binwidth = 0.05) + facet_grid(Tarih~.)

# When we try to see the relation of dollar Turkish Lira rate and "dolar alımı" search volume we see that while the rate is increasing constantly the trend is not buying Dollars unless some fluctuations happen in 2020. With the fluctuations and decrease in dollars more dollar purchase happened. ( we can see the fluctuations as the outliers)

ggplot(dolar, aes(kur,)) + geom_boxplot() + facet_grid(Tarih~.)
ggplot(dolarsv, aes(DolarAlimi,)) + geom_boxplot() + facet_grid(Hafta~.)

#3

faizyuzde <- read.csv("C:/Users/a_kok/Desktop/Dersler/IE 360/Kodlar/faizyuzde.csv")
kredibasvuru <- read.csv("C:/Users/a_kok/Desktop/Dersler/IE 360/Kodlar/kredibasvurusv.csv")


i = 1
while(i<=length(faizyuzde[["Tarih"]])){
  faizyuzde[i,"Tarih"] <- substr(faizyuzde[i,"Tarih"],4,10)
  i = i+1
}
i=1
while(i<=length(kredibasvuru[["Hafta"]])){
  kredibasvuru[i,"Hafta"] <- substr(kredibasvuru[i,"Hafta"],1,7)
  i = i+1
}

# as wee see from the histogram interest rates are increasing between 03.2019 to 06.2019 then it start to decrease with the government policies
ggplot(faizyuzde, aes(Faiz,)) + geom_histogram(binwidth = 0.1) + facet_grid(Tarih~.)


# while interest rates are decreasing there is a trend of searching for "kredi basvuru".
ggplot(faizyuzde, aes(Faiz,)) + geom_boxplot() + facet_grid(Tarih~.)
ggplot(kredibasvuru, aes(kredi.basvuru,)) + geom_boxplot() + facet_grid(Hafta~.)




```

